version: '3'

services:
  node-hello:
    build:
      context: .
      dockerfile: Dockerfile
    image: fortinmaxence/node-hello
    container_name: node-hello
    restart: unless-stopped
    ports:
      - "82:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
