version: '3'

services:
  node-goodbye:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-goodbye
    container_name: node-goodbye
    restart: unless-stopped
    ports:
      - "81:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
